name: CD Deploy

on: 
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: yarn    

    - name: Setup Node.js v22.4.0
      uses: actions/setup-node@v4
      with:
        node-version: 22.4.0
        cache: npm
        nvm: true
        nvm_path: '/root/.nvm/versions/node/v22.4.0/bin'


    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /var/www/popi.stagingaja.com/popi
          git pull origin dev
          git status
          node --version
          yarn
          yarn build
          pm2 restart popi-prod
