name: CD

on: 
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js v22.4.0
      uses: actions/setup-node@v4
      with:
        node-version: 22.4.0
        cache: 'yarn'

    - name: Deploy
      uses: appleboy/ssh-action@master
      run: |
      working-directory: /var/www/popi.stagingaja.com/popi
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /var/www/popi.stagingaja.com/popi
          git pull origin main
          git status
          node --version
          yarn install
          yarn build
          pm2 restart popi-prod